version: '3.8'

services:
  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.test
      - VIRTUAL_PORT=8000
      - NETWORK_ACCESS=internal

networks:
  default:
    external: true
    name: www-proxy-net
