#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER www-user
fi

if [ ! -z "$WWWGROUP" ]; then
    if [ -z $(getent group "$WWWGROUP") ]; then
        groupadd -g $WWWGROUP www-user
    fi
    usermod -g $WWWGROUP www-user
fi

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
